dist: xenial
language: python
python:
  - 3.6
addons:
  apt:
    packages:
      - make
      - postgresql-client-common
cache: pip
env:
  - POSTGRESQL_USER=postgres POSTGRESQL_PASSWORD=""
services:
  - docker
  - postgresql
  - redis
before_script:
  - psql -c 'create database jepostule;' -U postgres
install:
  - pip install -r requirements/dev.txt
script:
  - make test
  - make build
