version: "3"
services:

  ###### 3rd-party services
  postgres:
    image: postgres:11
    restart: unless-stopped
    environment:
      POSTGRES_USER: 'jepostule'
      POSTGRES_PASSWORD: 'mdp'
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:4-alpine
    command: redis-server --appendonly yes
    restart: unless-stopped
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis:/data

  zookeeper:
    image: zookeeper:3.4
    restart: unless-stopped
    environment:
      ZOO_MY_ID: 1
    ports:
      - "${ZOOKEEPER_PORT:-2181}:2181"
    volumes:
      - zookeeper_data:/data
      - zookeeper_datalog:/datalog

  kafka:
    image: kafka:latest
    restart: unless-stopped
    environment:
      LISTENERS: "${KAFKA_LISTENERS:-kafka}"
    ports:
      - "${KAFKA_PORT:-9092}:9092"
    depends_on:
      - zookeeper
    volumes:
      - kafka:/tmp/kafka-logs

  ###### Je Postule-specific services
  jepostule:
    image: jepostule:latest
    # restart: unless-stopped
    ports:
      - "${JEPOSTULE_PORT:-8000}:8000"
    depends_on:
      - kafka
      - postgres

  jepostule_consume_topics:
    image: jepostule:latest
    # restart: unless-stopped
    depends_on:
      - kafka
      - postgres
    command: ./manage.py consumetopics all

  jepostule_dequeue_delayed:
    image: jepostule:latest
    # restart: unless-stopped
    depends_on:
      - kafka
      - postgres
    command: ./manage.py dequeuedelayed

volumes:
  postgres:
  redis:
  kafka:
  zookeeper_data:
  zookeeper_datalog:
