# Generated by Django 2.1.2 on 2018-10-18 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_email', models.CharField(db_index=True, max_length=64)),
                ('employer_email', models.CharField(db_index=True, max_length=64)),
                ('job', models.CharField(max_length=256)),
                ('message', models.TextField(max_length=4000)),
                ('coordinates', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
