# Generated by Django 2.1.2 on 2018-11-08 16:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_email', models.CharField(db_index=True, max_length=64)),
                ('candidate_first_name', models.CharField(max_length=64)),
                ('candidate_last_name', models.CharField(max_length=64)),
                ('candidate_phone', models.CharField(max_length=32)),
                ('candidate_address', models.CharField(max_length=256)),
                ('candidate_peid', models.CharField(db_index=True, max_length=64)),
                ('employer_email', models.CharField(db_index=True, max_length=64)),
                ('employer_description', models.CharField(max_length=256)),
                ('message', models.TextField(max_length=4000)),
                ('job', models.CharField(max_length=128)),
                ('siret', models.CharField(db_index=True, max_length=14)),
                ('answer_uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobApplicationEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('name', models.CharField(choices=[('sent', "Envoyé à l'employeur"), ('confirmed', 'Confirmation envoyée au candidat')], db_index=True, max_length=32)),
                ('value', models.CharField(blank=True, max_length=256)),
                ('job_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='jepostulepipeline.JobApplication')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnswerInterview',
            fields=[
                ('answer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='jepostulepipeline.Answer')),
                ('employer_name', models.CharField(blank=True, max_length=128)),
                ('employer_email', models.EmailField(blank=True, max_length=128)),
                ('employer_phone', models.CharField(blank=True, max_length=32)),
                ('employer_address', models.CharField(blank=True, max_length=256)),
                ('message', models.TextField(blank=True)),
                ('datetime', models.DateTimeField(blank=True)),
                ('location', models.CharField(choices=[('onsite', "dans l'entreprise"), ('phone', 'par téléphone'), ('video', 'en visio conférence')], default='onsite', max_length=16)),
            ],
            options={
                'abstract': False,
            },
            bases=('jepostulepipeline.answer',),
        ),
        migrations.CreateModel(
            name='AnswerRejection',
            fields=[
                ('answer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='jepostulepipeline.Answer')),
                ('reason', models.CharField(choices=[('unknown', 'Je préfère ne pas expliciter'), ('profile', 'Le profil ne convient pas aux exigences du poste'), ('novacancy', 'Pas de poste disponible pour le moment')], default='unknown', max_length=16)),
                ('message', models.TextField(blank=True)),
            ],
            bases=('jepostulepipeline.answer',),
        ),
        migrations.CreateModel(
            name='AnswerRequestInfo',
            fields=[
                ('answer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='jepostulepipeline.Answer')),
                ('employer_name', models.CharField(blank=True, max_length=128)),
                ('employer_email', models.EmailField(blank=True, max_length=128)),
                ('employer_phone', models.CharField(blank=True, max_length=32)),
                ('employer_address', models.CharField(blank=True, max_length=256)),
                ('message', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('jepostulepipeline.answer',),
        ),
        migrations.AddField(
            model_name='answer',
            name='job_application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jepostulepipeline.JobApplication'),
        ),
    ]
