# Generated by Django 2.1.2 on 2018-10-18 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplicationEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('name', models.CharField(choices=[('sent', 'Sent to employer'), ('confirmed', 'Confirmed to candidate')], db_index=True, max_length=32)),
                ('value', models.CharField(blank=True, max_length=256)),
                ('job_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='pipeline.JobApplication')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
