# Generated by Django 2.1.2 on 2018-11-08 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jepostulepipeline', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerRejection',
            fields=[
                ('answer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='jepostulepipeline.Answer')),
                ('reason', models.CharField(choices=[('unknown', 'Je préfère ne pas expliciter'), ('profile', 'Pas de poste disponible pour le moment')], default='unknown', max_length=16)),
                ('message', models.TextField(blank=True)),
            ],
            bases=('jepostulepipeline.answer',),
        ),
    ]
