# Generated by Django 2.1.2 on 2018-11-14 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jepostulepipeline', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerinterview',
            name='datetime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='answerinterview',
            name='employer_address',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='answerinterview',
            name='employer_email',
            field=models.EmailField(max_length=128),
        ),
        migrations.AlterField(
            model_name='answerinterview',
            name='employer_name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='answerinterview',
            name='employer_phone',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='answerinterview',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='answerrejection',
            name='reason',
            field=models.CharField(choices=[('unknown', 'Je préfère ne pas expliciter'), ('novacancy', 'Pas de poste de ce type disponible pour le moment'), ('experience', 'Expérience non adaptée au poste au sein de notre entreprise'), ('skills', 'Compétences non adaptées au poste au sein de notre entreprise'), ('education', 'Formations/Qualifications insuffisantes/inadaptées au poste au sein de notre entreprise')], default='unknown', max_length=16),
        ),
        migrations.AlterField(
            model_name='answerrequestinfo',
            name='employer_address',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='answerrequestinfo',
            name='employer_email',
            field=models.EmailField(max_length=128),
        ),
        migrations.AlterField(
            model_name='answerrequestinfo',
            name='employer_name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='answerrequestinfo',
            name='employer_phone',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='answerrequestinfo',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='jobapplicationevent',
            name='name',
            field=models.CharField(choices=[('sent', "Envoyé à l'employeur"), ('confirmed', 'Confirmation envoyée au candidat'), ('answered', 'Réponse envoyée au candidat')], db_index=True, max_length=32),
        ),
    ]
