# Generated by Django 2.1.2 on 2018-11-14 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jepostuleauth', '0001_initial'),
        ('jepostulepipeline', '0002_auto_20181114_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='client_platform',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='jepostuleauth.ClientPlatform'),
            preserve_default=False,
        ),
    ]
