# Generated by Django 2.1.2 on 2018-11-08 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jepostulepipeline', '0002_answerrejection'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerRequestInfo',
            fields=[
                ('answer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='jepostulepipeline.Answer')),
                ('employer_name', models.CharField(blank=True, max_length=128)),
                ('employer_email', models.EmailField(blank=True, max_length=128)),
                ('employer_phone', models.CharField(blank=True, max_length=32)),
                ('employer_address', models.CharField(blank=True, max_length=256)),
                ('message', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('jepostulepipeline.answer',),
        ),
        migrations.AlterField(
            model_name='answerrejection',
            name='reason',
            field=models.CharField(choices=[('unknown', 'Je préfère ne pas expliciter'), ('profile', 'Le profil ne convient pas aux exigences du poste'), ('novacancy', 'Pas de poste disponible pour le moment')], default='unknown', max_length=16),
        ),
    ]
