# Generated by Django 2.1.2 on 2019-02-06 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jepostulepipeline', '0003_jobapplication_client_platform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.BigIntegerField(db_index=True, null=True)),
                ('status', models.CharField(choices=[('sent', 'Envoyé'), ('opened', 'Ouvert'), ('spam', 'Mis en spam'), ('blocked', 'Bloqué (non envoyé)'), ('bounced', 'Bloqué (non reçu)')], db_index=True, max_length=16)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jepostulepipeline.JobApplicationEvent')),
            ],
        ),
    ]
