# Generated by Django 2.1.7 on 2019-03-22 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jepostulepipeline', '0004_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answerinterview',
            name='datetime',
        ),
        migrations.AddField(
            model_name='answerinterview',
            name='date',
            field=models.CharField(default='n/a', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answerinterview',
            name='time',
            field=models.CharField(default='n/a', max_length=128),
            preserve_default=False,
        ),
    ]
