# Generated by Django 2.1.7 on 2019-04-04 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jepostulepipeline', '0004_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='candidate_rome_code',
            field=models.CharField(default='', max_length=5),
            preserve_default=False,
        ),
    ]
