# Generated by Django 2.1.7 on 2019-04-18 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jepostulepipeline', '0005_jobapplication_candidate_rome_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='candidate_rome_code',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
    ]
