# Generated by Django 2.2 on 2019-05-16 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jepostulepipeline', '0006_auto_20190418_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerinterview',
            name='employer_address',
            field=models.CharField(blank=True, max_length=256, verbose_name="Adresse de l'entreprise"),
        ),
        migrations.AlterField(
            model_name='answerinterview',
            name='employer_email',
            field=models.EmailField(blank=True, max_length=128, verbose_name='Email du recruteur'),
        ),
        migrations.AlterField(
            model_name='answerinterview',
            name='employer_name',
            field=models.CharField(blank=True, max_length=128, verbose_name='Prénom et nom du recruteur'),
        ),
        migrations.AlterField(
            model_name='answerinterview',
            name='employer_phone',
            field=models.CharField(blank=True, max_length=32, verbose_name='Numéro de téléphone'),
        ),
        migrations.AlterField(
            model_name='answerrequestinfo',
            name='employer_address',
            field=models.CharField(blank=True, max_length=256, verbose_name="Adresse de l'entreprise"),
        ),
        migrations.AlterField(
            model_name='answerrequestinfo',
            name='employer_email',
            field=models.EmailField(blank=True, max_length=128, verbose_name='Email du recruteur'),
        ),
        migrations.AlterField(
            model_name='answerrequestinfo',
            name='employer_name',
            field=models.CharField(blank=True, max_length=128, verbose_name='Prénom et nom du recruteur'),
        ),
        migrations.AlterField(
            model_name='answerrequestinfo',
            name='employer_phone',
            field=models.CharField(blank=True, max_length=32, verbose_name='Numéro de téléphone'),
        ),
    ]
