# Generated by Django 2.2.2 on 2019-06-19 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jepostulepipeline', '0008_auto_20190527_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerinterview',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='answerrequestinfo',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
