# Generated by Django 2.2.5 on 2019-09-16 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jepostulepipeline', '0009_auto_20190619_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='candidate_peam_access_token',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
