# Generated by Django 2.1.2 on 2018-11-05 09:39

from django.db import migrations, models
import jepostule.auth.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientPlatform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=32, unique=True)),
                ('client_secret', models.CharField(default=jepostule.auth.models.generate_secret_key, max_length=32)),
            ],
        ),
    ]
